### PR TITLE
Fixing "self." caused by https://github.com/joernio/cpgqls-client-python/pull/14

### PR DESCRIPTION
**Pull request by rakovskij-stanislav**
Tested this - works fine.

This PR fixes https://github.com/joernio/cpgqls-client-python/pull/14

### CODE REVIEW

**Review by mpollmeier — APPROVED** [review]
thanks!

**Comment by mpollmeier** [comment]
master build is green now

**Comment by rakovskij-stanislav** [comment]
@mpollmeier https://github.com/joernio/cpgqls-client-python/actions/runs/9365828057/job/25781897596#step:6:76

As I can see, you need to increment version of this package in [setup.py](https://github.com/joernio/cpgqls-client-python/blob/master/setup.py#L13) to allow this changes to be published on PyPI

**Comment by mpollmeier** [comment]
https://github.com/joernio/cpgqls-client-python/pull/16

PR build doesn't work any longer either... I'm not sure if we even have a use case for it, so this project is not in a healthy state from a lot of angles... :(
Will merge the version upgrade as you suggested, thanks for your help and sorry about the circumstances, this isn't really to the standards we like to adhere to.

**Comment by mpollmeier** [comment]
I guess that's me saying @ursachec we miss you 😿

**Comment by rakovskij-stanislav** [comment]
It looks like credentials does not work. Probably because an account had no 2FA, and according [to this accident](https://blog.pypi.org/posts/2024-04-03-user-account-access/) PyPI admins invalidated the credentials.

**Pull request merged**
